import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  server: {
    NODE_ENV: z.enum(["development", "test", "production"]).default("development"),
    SUPABASE_SERVICE_ROLE_KEY: z.string().min(1, "SUPABASE_SERVICE_ROLE_KEY is required"),
    STRIPE_SECRET_KEY: z.string().min(1, "STRIPE_SECRET_KEY is required"),
    STRIPE_WEBHOOK_SECRET: z.string().min(1, "STRIPE_WEBHOOK_SECRET is required"),
    LIVEBLOCKS_SECRET_KEY: z.string().min(1, "LIVEBLOCKS_SECRET_KEY is required"),
    ARCJET_KEY: z.string().optional(),
    CANNY_API_KEY: z.string().optional(),
    POSTHOG_API_KEY: z.string().optional(),
    KEEPALIVE_ENDPOINT: z.string().optional(),
    KEEPALIVE_API_KEY: z.string().optional(),
    CORS_ALLOWED_ORIGIN: z.string().url().optional(),
    SENTRY_DSN: z.string().url().optional(),
    SENTRY_ENVIRONMENT: z.string().optional(),
    SENTRY_TRACES_SAMPLE_RATE: z.string().optional(),
    SENTRY_PROFILES_SAMPLE_RATE: z.string().optional(),
    SENTRY_TRACE_PROPAGATION_TARGETS: z.string().optional(),
    SENTRY_RELEASE: z.string().optional(),
    SENTRY_REPLAYS_SESSION_SAMPLE_RATE: z.string().optional(),
    SENTRY_REPLAYS_ON_ERROR_SAMPLE_RATE: z.string().optional(),
    VERCEL_GIT_COMMIT_SHA: z.string().optional(),
  },
  client: {
    NEXT_PUBLIC_SUPABASE_URL: z.string().url(),
    NEXT_PUBLIC_SUPABASE_ANON_KEY: z.string().min(1, "NEXT_PUBLIC_SUPABASE_ANON_KEY is required"),
    NEXT_PUBLIC_APP_URL: z.string().url().default("http://localhost:3000"),
    NEXT_PUBLIC_VERCEL_ENV: z.enum(["development", "preview", "production"]).default("development"),
    NEXT_PUBLIC_VERCEL_URL: z.string().default("localhost:3000"),
    NEXT_PUBLIC_VERCEL_GIT_COMMIT_SHA: z.string().optional(),
    NEXT_PUBLIC_SENTRY_TUNNEL: z.string().default("/monitoring"),
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: z
      .string()
      .min(1, "NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY is required"),
    NEXT_PUBLIC_STRIPE_STARTED_MONTHLY_PRICE_ID: z
      .string()
      .min(1, "NEXT_PUBLIC_STRIPE_STARTED_MONTHLY_PRICE_ID is required"),
    NEXT_PUBLIC_STRIPE_STARTED_YEARLY_PRICE_ID: z
      .string()
      .min(1, "NEXT_PUBLIC_STRIPE_STARTED_YEARLY_PRICE_ID is required"),
    NEXT_PUBLIC_STRIPE_PRO_MONTHLY_PRICE_ID: z
      .string()
      .min(1, "NEXT_PUBLIC_STRIPE_PRO_MONTHLY_PRICE_ID is required"),
    NEXT_PUBLIC_STRIPE_PRO_YEARLY_PRICE_ID: z
      .string()
      .min(1, "NEXT_PUBLIC_STRIPE_PRO_YEARLY_PRICE_ID is required"),
    NEXT_PUBLIC_POSTHOG_KEY: z.string().optional(),
    NEXT_PUBLIC_POSTHOG_HOST: z.string().url().default("https://app.posthog.com"),
    NEXT_PUBLIC_POSTHOG_ENABLE_LOCAL: z.enum(["true", "false"]).default("false"),
    NEXT_PUBLIC_SITE_URL: z.string().url().optional(),
    NEXT_PUBLIC_HOTJAR_SITE_ID: z.string().optional(),
    NEXT_PUBLIC_EXPORT_EXPERIMENT: z.string().default("control"),
    NEXT_PUBLIC_TRANSITION_EXPERIMENT: z.string().default("control"),
    NEXT_PUBLIC_LIVEBLOCKS_PUBLIC_API_KEY: z.string().optional(),
  },
  runtimeEnv: {
    NODE_ENV: process.env.NODE_ENV,
    SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY,
    STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
    STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET,
    LIVEBLOCKS_SECRET_KEY: process.env.LIVEBLOCKS_SECRET_KEY,
    ARCJET_KEY: process.env.ARCJET_KEY,
    CANNY_API_KEY: process.env.CANNY_API_KEY,
    POSTHOG_API_KEY: process.env.POSTHOG_API_KEY,
    KEEPALIVE_ENDPOINT: process.env.KEEPALIVE_ENDPOINT,
    KEEPALIVE_API_KEY: process.env.KEEPALIVE_API_KEY,
    CORS_ALLOWED_ORIGIN: process.env.CORS_ALLOWED_ORIGIN,
    SENTRY_DSN: process.env.SENTRY_DSN,
    SENTRY_ENVIRONMENT: process.env.SENTRY_ENVIRONMENT,
    SENTRY_TRACES_SAMPLE_RATE: process.env.SENTRY_TRACES_SAMPLE_RATE,
    SENTRY_PROFILES_SAMPLE_RATE: process.env.SENTRY_PROFILES_SAMPLE_RATE,
    SENTRY_TRACE_PROPAGATION_TARGETS: process.env.SENTRY_TRACE_PROPAGATION_TARGETS,
    SENTRY_RELEASE: process.env.SENTRY_RELEASE,
    SENTRY_REPLAYS_SESSION_SAMPLE_RATE: process.env.SENTRY_REPLAYS_SESSION_SAMPLE_RATE,
    SENTRY_REPLAYS_ON_ERROR_SAMPLE_RATE: process.env.SENTRY_REPLAYS_ON_ERROR_SAMPLE_RATE,
    VERCEL_GIT_COMMIT_SHA: process.env.VERCEL_GIT_COMMIT_SHA,
    NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
    NEXT_PUBLIC_SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
    NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
    NEXT_PUBLIC_VERCEL_ENV: process.env.NEXT_PUBLIC_VERCEL_ENV,
    NEXT_PUBLIC_VERCEL_URL: process.env.NEXT_PUBLIC_VERCEL_URL,
    NEXT_PUBLIC_VERCEL_GIT_COMMIT_SHA: process.env.NEXT_PUBLIC_VERCEL_GIT_COMMIT_SHA,
    NEXT_PUBLIC_SENTRY_TUNNEL: process.env.NEXT_PUBLIC_SENTRY_TUNNEL,
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY,
    NEXT_PUBLIC_STRIPE_STARTED_MONTHLY_PRICE_ID:
      process.env.NEXT_PUBLIC_STRIPE_STARTED_MONTHLY_PRICE_ID,
    NEXT_PUBLIC_STRIPE_STARTED_YEARLY_PRICE_ID:
      process.env.NEXT_PUBLIC_STRIPE_STARTED_YEARLY_PRICE_ID,
    NEXT_PUBLIC_STRIPE_PRO_MONTHLY_PRICE_ID: process.env.NEXT_PUBLIC_STRIPE_PRO_MONTHLY_PRICE_ID,
    NEXT_PUBLIC_STRIPE_PRO_YEARLY_PRICE_ID: process.env.NEXT_PUBLIC_STRIPE_PRO_YEARLY_PRICE_ID,
    NEXT_PUBLIC_POSTHOG_KEY: process.env.NEXT_PUBLIC_POSTHOG_KEY,
    NEXT_PUBLIC_POSTHOG_HOST: process.env.NEXT_PUBLIC_POSTHOG_HOST,
    NEXT_PUBLIC_POSTHOG_ENABLE_LOCAL: process.env.NEXT_PUBLIC_POSTHOG_ENABLE_LOCAL,
    NEXT_PUBLIC_SITE_URL: process.env.NEXT_PUBLIC_SITE_URL,
    NEXT_PUBLIC_HOTJAR_SITE_ID: process.env.NEXT_PUBLIC_HOTJAR_SITE_ID,
    NEXT_PUBLIC_EXPORT_EXPERIMENT: process.env.NEXT_PUBLIC_EXPORT_EXPERIMENT,
    NEXT_PUBLIC_TRANSITION_EXPERIMENT: process.env.NEXT_PUBLIC_TRANSITION_EXPERIMENT,
    NEXT_PUBLIC_LIVEBLOCKS_PUBLIC_API_KEY: process.env.NEXT_PUBLIC_LIVEBLOCKS_PUBLIC_API_KEY,
  },
  skipValidation: !!process.env.SKIP_ENV_VALIDATION,
  emptyStringAsUndefined: true,
});
